import React, { useEffect, useState } from "react";
import jsPDF from "jspdf";
import { listEsignRequests, createEsignRequest, voidEsignRequest, deleteEsignRequest, getEsignRequest } from "./partnerEsignDb.js";
import { listDocuments, uploadDocument } from "./partnerDb.js";

const NV = "#1e3a5f", BL = "#1B91FE", MUTED = "#64748b", LINE = "#e6eaf0";
const TONE = { draft: ["#f1f5f9", "#475569"], sent: ["#fff7ed", "#b45309"], signed: ["#ecfdf5", "#15803d"], void: ["#fef2f2", "#b91c1c"] };

function triggerDownload(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}
function fmtDateTime(s) { if (!s) return ""; try { return new Date(s).toLocaleString(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }); } catch (e) { return s; } }

/* ---------------- Signature certificate (jsPDF) ---------------- */
function buildCertificate(req, firm) {
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const margin = 54;
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  let y = margin;
  const ensure = (h) => { if (y + h > pageH - margin) { pdf.addPage(); y = margin; } };

  pdf.setFont("helvetica", "bold"); pdf.setFontSize(16);
  pdf.text(String(firm?.name || "Closing Desk"), margin, y);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(13); pdf.setTextColor(120);
  pdf.text("SIGNATURE CERTIFICATE", pageW - margin, y, { align: "right" });
  pdf.setTextColor(0);
  y += 26;
  pdf.setDrawColor(220); pdf.line(margin, y, pageW - margin, y); y += 22;

  pdf.setFont("helvetica", "bold"); pdf.setFontSize(12);
  pdf.text("Document", margin, y); y += 16;
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(11);
  pdf.text(pdf.splitTextToSize(String(req.title || "Document"), pageW - 2 * margin), margin, y); y += 18;
  pdf.setTextColor(90); pdf.setFontSize(10);
  pdf.text(`Request created: ${fmtDateTime(req.created_at) || "—"}`, margin, y); y += 13;
  if (req.completed_at) { pdf.text(`Completed: ${fmtDateTime(req.completed_at)}`, margin, y); y += 13; }
  pdf.setTextColor(0);
  y += 14;

  (req.signers || []).forEach((s, idx) => {
    ensure(120);
    pdf.setDrawColor(230); pdf.line(margin, y, pageW - margin, y); y += 18;
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(11.5);
    pdf.text(`${idx + 1}. ${s.name || "Signer"}${s.role ? "  (" + s.role + ")" : ""}`, margin, y); y += 15;
    pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); pdf.setTextColor(90);
    if (s.email) { pdf.text(s.email, margin, y); y += 13; }
    if (s.status === "signed") {
      pdf.text(`Signed: ${fmtDateTime(s.signed_at) || "—"}`, margin, y); y += 13;
      if (s.ip) { pdf.text(`IP address: ${s.ip}`, margin, y); y += 13; }
    } else {
      pdf.setTextColor(180, 83, 9);
      pdf.text("Status: Pending — not yet signed", margin, y); y += 13;
    }
    pdf.setTextColor(0);
    y += 6;

    if (s.status === "signed" && s.signature_data) {
      if (s.signature_type === "drawn" && /^data:image\//.test(s.signature_data)) {
        ensure(70);
        try { pdf.addImage(s.signature_data, "PNG", margin, y, 200, 60); } catch (e) { /* skip bad image */ }
        y += 66;
      } else {
        ensure(40);
        pdf.setFont("times", "italic"); pdf.setFontSize(22);
        pdf.text(String(s.signature_data), margin, y + 22); pdf.setFont("helvetica", "normal"); pdf.setFontSize(10);
        y += 40;
      }
    }
    y += 8;
  });

  ensure(40);
  pdf.setDrawColor(220); pdf.line(margin, y, pageW - margin, y); y += 16;
  pdf.setFontSize(9); pdf.setTextColor(120);
  pdf.text(pdf.splitTextToSize("This certificate records the electronic signatures applied to the above document, including each signer's name, the time of signing, and the IP address from which they signed. Generated by Closing Desk.", pageW - 2 * margin), margin, y);
  pdf.setTextColor(0);

  return pdf.output("blob");
}

/* ---------------- Send-for-signature form ---------------- */
function SendForm({ matter, onClose, onCreated }) {
  const [docs, setDocs] = useState([]);
  const [title, setTitle] = useState("");
  const [docPath, setDocPath] = useState("");
  const [signers, setSigners] = useState([{ name: "", email: "", role: "" }]);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [fresh, setFresh] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => { (async () => { try { setDocs(await listDocuments(matter.id)); } catch (e) { /* ignore */ } })(); }, [matter.id]);

  const setSigner = (i, patch) => setSigners((p) => p.map((s, idx) => idx === i ? { ...s, ...patch } : s));
  const addSigner = () => setSigners((p) => [...p, { name: "", email: "", role: "" }]);
  const removeSigner = (i) => setSigners((p) => p.length > 1 ? p.filter((_, idx) => idx !== i) : p);

  const create = async () => {
    setErr("");
    const named = signers.filter((s) => (s.name || "").trim() || (s.email || "").trim());
    if (!named.length) { setErr("Add at least one signer."); return; }
    const chosen = docs.find((d) => d.storage_path === docPath);
    const finalTitle = title.trim() || (chosen && chosen.name) || "Document";
    setBusy(true);
    try {
      const { token } = await createEsignRequest(matter.firm_id, matter.id, { title: finalTitle, doc_path: docPath || null, signers: named });
      setFresh({ url: `${window.location.origin}/sign/${token}` });
      onCreated && onCreated();
    } catch (e) { setErr(e.message || String(e)); }
    setBusy(false);
  };
  const copy = (url) => { try { navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1600); } catch (e) { /* ignore */ } };

  const inp = { width: "100%", padding: "9px 11px", border: `1px solid ${LINE}`, borderRadius: 8, fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box" };
  const lbl = { fontSize: 11, color: MUTED, fontWeight: 600, marginBottom: 3, display: "block" };

  return (
    <div onClick={(e) => e.target === e.currentTarget && onClose()} style={{ position: "fixed", inset: 0, background: "rgba(15,23,42,.5)", display: "flex", alignItems: "center", justifyContent: "center", padding: 22, zIndex: 60 }}>
      <div style={{ background: "#fff", borderRadius: 16, width: "100%", maxWidth: 540, maxHeight: "92vh", overflow: "auto", boxShadow: "0 12px 40px rgba(16,24,40,.2)" }}>
        <div style={{ padding: "16px 20px", borderBottom: `1px solid ${LINE}`, display: "flex", justifyContent: "space-between", alignItems: "center", position: "sticky", top: 0, background: "#fff" }}>
          <div style={{ fontFamily: "Fraunces,serif", fontWeight: 600, fontSize: 18 }}>Send for signature</div>
          <button onClick={onClose} style={{ background: "none", border: "none", fontSize: 22, color: "#9ca3af", cursor: "pointer" }}>×</button>
        </div>
        <div style={{ padding: 20 }}>
          {fresh ? (
            <div>
              <div style={{ background: "#ecfdf5", border: "1px solid #a7f3d0", borderRadius: 10, padding: "14px 16px", marginBottom: 8 }}>
                <div style={{ fontSize: 12.5, fontWeight: 700, color: "#065f46", marginBottom: 8 }}>Signing link ready — send it to your signer</div>
                <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                  <input readOnly value={fresh.url} onFocus={(e) => e.target.select()} style={{ ...inp, background: "#fff", fontSize: 12 }} />
                  <button onClick={() => copy(fresh.url)} style={{ padding: "9px 14px", background: "#065f46", color: "#fff", border: "none", borderRadius: 8, fontSize: 12.5, fontWeight: 600, cursor: "pointer", whiteSpace: "nowrap" }}>{copied ? "Copied ✓" : "Copy"}</button>
                </div>
              </div>
              <div style={{ fontSize: 11.5, color: MUTED, marginBottom: 16 }}>Anyone with this link can open the document and sign as one of the named signers. You can re-copy it later from the list, or cancel it.</div>
              <button onClick={onClose} style={{ width: "100%", padding: "11px", background: BL, color: "#fff", border: "none", borderRadius: 9, fontWeight: 600, fontSize: 14, cursor: "pointer" }}>Done</button>
            </div>
          ) : (
            <>
              <label style={lbl}>Document from this file (optional)</label>
              <select value={docPath} onChange={(e) => setDocPath(e.target.value)} style={{ ...inp, marginBottom: 12 }}>
                <option value="">— none / sign without an attached file —</option>
                {docs.map((d) => <option key={d.id} value={d.storage_path}>{d.name}</option>)}
              </select>

              <label style={lbl}>Title</label>
              <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Retainer agreement" style={{ ...inp, marginBottom: 14 }} />

              <div style={{ fontSize: 11.5, color: MUTED, fontWeight: 600, textTransform: "uppercase", letterSpacing: ".04em", marginBottom: 8 }}>Signers</div>
              {signers.map((s, i) => (
                <div key={i} style={{ display: "flex", gap: 6, marginBottom: 8, alignItems: "center" }}>
                  <input value={s.name} onChange={(e) => setSigner(i, { name: e.target.value })} placeholder="Name" style={{ ...inp, flex: 1.3 }} />
                  <input value={s.email} onChange={(e) => setSigner(i, { email: e.target.value })} placeholder="Email (optional)" style={{ ...inp, flex: 1.3 }} />
                  <input value={s.role} onChange={(e) => setSigner(i, { role: e.target.value })} placeholder="Role" style={{ ...inp, flex: 0.8 }} />
                  <button onClick={() => removeSigner(i)} style={{ width: 24, background: "none", border: "none", color: "#b91c1c", fontSize: 16, cursor: "pointer", flexShrink: 0 }}>×</button>
                </div>
              ))}
              <button onClick={addSigner} style={{ fontSize: 12.5, color: BL, fontWeight: 600, background: "none", border: "none", cursor: "pointer", padding: "2px 0 12px" }}>＋ Add signer</button>

              {err && <div style={{ fontSize: 12.5, color: "#b91c1c", marginBottom: 10 }}>{err}</div>}
              <button onClick={create} disabled={busy} style={{ width: "100%", padding: "12px", background: busy ? "#9ca3af" : BL, color: "#fff", border: "none", borderRadius: 9, fontWeight: 600, fontSize: 14, cursor: busy ? "default" : "pointer" }}>{busy ? "Creating…" : "Create signing link"}</button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

/* ---------------- Panel ---------------- */
export function MatterEsignPanel({ matter, firm }) {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [busyId, setBusyId] = useState("");
  const [copiedId, setCopiedId] = useState("");
  const [err, setErr] = useState("");

  const load = async () => { setLoading(true); try { setRows(await listEsignRequests(matter.id)); } catch (e) { console.error(e); } setLoading(false); };
  useEffect(() => { load(); /* eslint-disable-next-line */ }, [matter.id]);

  const linkOf = (r) => `${window.location.origin}/sign/${r.token}`;
  const copy = (r) => { try { navigator.clipboard.writeText(linkOf(r)); setCopiedId(r.id); setTimeout(() => setCopiedId(""), 1600); } catch (e) { /* ignore */ } };
  const cancel = async (r) => { if (!window.confirm(`Cancel the signature request "${r.title}"? The link stops working.`)) return; try { await voidEsignRequest(r.id); await load(); } catch (e) { setErr(e.message || String(e)); } };
  const remove = async (r) => { if (!window.confirm(`Delete "${r.title}" and its signatures? This can't be undone.`)) return; try { await deleteEsignRequest(r.id); await load(); } catch (e) { setErr(e.message || String(e)); } };

  const downloadCert = async (r) => {
    setBusyId(r.id); setErr("");
    try {
      const full = await getEsignRequest(r.id);
      const blob = buildCertificate(full, firm);
      const base = `Signature Certificate - ${(full.title || "document").replace(/[^\w.\- ]+/g, "_")}`;
      triggerDownload(blob, base + ".pdf");
      try { await uploadDocument(matter.firm_id, matter, new File([blob], base + ".pdf", { type: "application/pdf" })); } catch (e) { /* vault save best-effort */ }
    } catch (e) { setErr(e.message || String(e)); }
    setBusyId("");
  };

  return (
    <div style={{ background: "#fff", border: `1px solid ${LINE}`, borderRadius: 14, padding: 18, marginTop: 16, maxWidth: 560 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }}>
        <div style={{ fontWeight: 600, fontSize: 14 }}>Signatures</div>
        <button onClick={() => setSending(true)} style={{ padding: "7px 13px", background: BL, color: "#fff", border: "none", borderRadius: 8, fontSize: 12.5, fontWeight: 600, cursor: "pointer" }}>＋ Send for signature</button>
      </div>
      <div style={{ fontSize: 11.5, color: MUTED, marginBottom: 12 }}>Built-in e-sign. Pick a document, add signers, share the link. A signed certificate is generated when everyone signs.</div>
      {err && <div style={{ fontSize: 12, color: "#b91c1c", marginBottom: 8 }}>{err}</div>}

      {loading ? <div style={{ fontSize: 12.5, color: "#9ca3af" }}>Loading…</div>
        : rows.length === 0 ? <div style={{ fontSize: 12.5, color: "#9ca3af", padding: "4px 0" }}>No signature requests yet.</div>
          : <div style={{ display: "flex", flexDirection: "column" }}>
            {rows.map((r) => {
              const [bg, col] = TONE[r.status] || TONE.sent;
              const signedCount = (r.signers || []).filter((s) => s.status === "signed").length;
              const total = (r.signers || []).length;
              const anySigned = signedCount > 0;
              return (
                <div key={r.id} style={{ padding: "11px 0", borderTop: "1px solid #eef1f6" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <div style={{ minWidth: 0, flex: 1 }}>
                      <div style={{ fontSize: 13.5, fontWeight: 600, color: NV, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.title}</div>
                      <div style={{ fontSize: 11.5, color: MUTED }}>{signedCount}/{total} signed · {fmtDateTime(r.created_at)}</div>
                    </div>
                    <span style={{ fontSize: 11, fontWeight: 700, padding: "3px 10px", borderRadius: 20, background: bg, color: col, textTransform: "capitalize" }}>{r.status}</span>
                  </div>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: 5, margin: "8px 0 2px" }}>
                    {(r.signers || []).map((s) => (
                      <span key={s.id} style={{ fontSize: 11, fontWeight: 600, padding: "2px 8px", borderRadius: 20, background: s.status === "signed" ? "#ecfdf5" : "#f1f5f9", color: s.status === "signed" ? "#15803d" : "#64748b" }}>{s.name || "Signer"}{s.status === "signed" ? " ✓" : ""}</span>
                    ))}
                  </div>
                  <div style={{ display: "flex", gap: 8, marginTop: 8, flexWrap: "wrap" }}>
                    {r.status !== "void" && <button onClick={() => copy(r)} style={{ padding: "5px 11px", background: "#fff", border: `1px solid ${LINE}`, borderRadius: 7, fontSize: 11.5, fontWeight: 600, color: NV, cursor: "pointer" }}>{copiedId === r.id ? "Copied ✓" : "Copy link"}</button>}
                    {anySigned && <button onClick={() => downloadCert(r)} disabled={busyId === r.id} style={{ padding: "5px 11px", background: "#fff", border: `1px solid ${LINE}`, borderRadius: 7, fontSize: 11.5, fontWeight: 600, color: NV, cursor: "pointer" }}>{busyId === r.id ? "…" : "Certificate PDF"}</button>}
                    {r.status !== "void" && r.status !== "signed" && <button onClick={() => cancel(r)} style={{ padding: "5px 11px", background: "#fff", border: `1px solid ${LINE}`, borderRadius: 7, fontSize: 11.5, fontWeight: 500, color: MUTED, cursor: "pointer" }}>Cancel</button>}
                    <button onClick={() => remove(r)} style={{ padding: "5px 9px", background: "#fff", border: "1px solid #fecaca", color: "#b91c1c", borderRadius: 7, fontSize: 11.5, cursor: "pointer" }}>✕</button>
                  </div>
                </div>
              );
            })}
          </div>}

      {sending && <SendForm matter={matter} onClose={() => setSending(false)} onCreated={load} />}
    </div>
  );
}
